# Site settings
title: jover
email: hello@jover.be
description: ""
baseurl: ""
url: "http://www.jover.be"

# Social
github_username:   jover
linkedin_username: jochenverdeyen
twitter_username:  jochenverdeyen

# Build settings
markdown: kramdown

# Excludes
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README"]

# Includes
include: []

# Time Zone
timezone: "Europe/Brussels"

# Encoding
encoding: "UTF-8"

# Permalink
permalink: pretty

# Pagination
paginate: 5
paginate_path: "/blog/:num/"

# Excerpt separator
excerpt_separator: <!--more-->

# Navigation
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Contact
  url: /contact/
