# Site settings
title: jover
email: hello@jover.be
description: ""
baseurl: ""
url: "http://www.jover.be"

# Gems
gems:
- jekyll-sitemap

# Social
drupal_username:   jover
github_username:   jover
linkedin_username: jochenverdeyen
twitter_username:  jochenverdeyen

# Build settings
markdown: kramdown

# Excludes
exclude: ["node_modules", "CNAME", "Gemfile", "Gemfile.lock", "gulpfile.js", "package.json", "README"]

# Includes
include: []

# Time Zone
timezone: "Europe/Brussels"

# Encoding
encoding: "UTF-8"

# Permalink
permalink: pretty

# Pagination
paginate: 5
paginate_path: "/blog/:num/"

# Excerpt separator
excerpt_separator: <!--more-->

# Navigation
navigation:
- text: Home
  url: /
#- text: About
#  url: /about/
#- text: Archive
#  url: /archive/
- text: Contact
  url: /contact/
