# Site settings
title: Jover Blog
email: hello@jover.be
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jover.be"
twitter_username: jochenverdeyen
github_username:  jekyll

# Build settings
markdown: kramdown

# Source & destination
source: project
destination: www

# Excludes
exclude: []

# Includes
include: [".htaccess"]

# Time Zone
timezone: "Europe/Brussels"

# Encoding
encoding: "UTF-8"
